// SIGN UP
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

// LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const STORE_TOKEN = 'STORE_TOKEN';

export const LOG_OUT = 'LOG_OUT'

//APP ACTIONS

// {{ QUESTIONS }}
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_FAIL = 'FETCH_QUESTIONS_FAIL';

export const FETCH_QUESTION = 'FETCH_QUESTION';
export const FETCH_QUESTION_SUCCESS = 'FETCH_QUESTION_SUCCESS';
export const FETCH_QUESTION_FAIL = 'FETCH_QUESTION_FAIL';


// {{ ANSWER }}

export const FETCH_ANSWERS = 'FETCH_ANSWERS';
export const FETCH_ANSWER = 'FETCH_ANSWER';
export const FETCH_MAIN_ANSWER = 'FETCH_MAIN_ANSWER';

export const FETCH_MAIN_ANSWER_SUCCESS = 'FETCH_MAIN_ANSWER_SUCCESS';
export const FETCH_ANSWERS_SUCCESS = 'FETCH_ANSWERS_SUCCESS';
export const FETCH_ANSWER_SUCCESS = 'FETCH_ANSWER_SUCCESS';

export const FETCH_MAIN_ANSWER_FAIL = 'FETCH_MAIN_ANSWER_FAIL';
export const FETCH_ANSWER_FAIL = 'FETCH_ANSWER_FAIL';
export const FETCH_ANSWERS_FAIL = 'FETCH_ANSWERS_FAIL';


// {{ COMMENTS }}

export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAIL = 'FETCH_COMMENTS_FAIL';

export const FETCH_COMMENT = 'FETCH_COMMENT';
export const FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS';
export const FETCH_COMMENT_FAIL = 'FETCH_COMMENT_FAIL';

